project:
  type: website
  output-dir: docs

website:
  title: "Cheong Jian Wei"
  site-url: "https://jianweicheong.github.io"
  description: "Jian Wei's website"
  favicon: media/me_crop.png
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/jianweicheong/jianweicheong.github.io
  repo-actions: issue
  search:
    location: navbar
    type: textbox
  navbar:
    pinned: true
    collapse: true
    right:
      - href: posts.xml
        icon: rss
    left:
      - href: index.qmd
        text: home
      - href: posts.qmd
        text: posts
      - href: cv.qmd
        text: cv
      - href: contact.qmd
        text: contact

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



