project:
  type: website
  output-dir: docs

website:
  title: "Cheong Jian Wei"
  site-url: "https://jianweicheong.github.io"
  description: "Jian Wei's website"
  favicon: media/me_crop.png
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/jianweicheong/jianweicheong.github.io
  repo-actions: issue
  image: media/me_crop.png
  open-graph: true
  search:
    location: navbar
    type: textbox
  navbar:
    pinned: true
    collapse: true
    right:
      - href: posts.xml
        icon: rss
    left:
      - href: index.qmd
        text: home
      - href: posts.qmd
        text: posts
      - href: cv.qmd
        text: cv
      - href: contact.qmd
        text: contact

format:
  html:
    filters:
      - lightbox
    lightbox: auto
    theme:
      light: [simplex, theme-light.scss]
      dark: [simplex, theme-dark.scss]
    mainfont: sans-serif
    linestretch: 1.4
    toc: true
    toc-location: left
    reference-location: margin
    citation-location: margin



