---
title: Good software I use and recommend
date: 2020-02-15T00:00:00+08:00
categories: [software]
draft: true
---

Perhaps you might find this list useful when looking for suggestions or alternatives on which software to use, or at the very least you might come across something that you need but have never heard of.
It should be noted however, that I use Linux and thus some software might not be available on Windows or Mac.

**Web Browser**
: Mozilla Firefox is a free and open-source browser developed by the Mozilla Foundation. Mozilla cares about internet privacy, and the open web. It is certainly worth supporting them by using Firefox. If you haven't, take look at their Manifesto.


**Mail Client**
: Mozilla Thunderbird is highly customisable, and have add-ons, similar to a browser, allowing you to download themes or extensions to enhance your experience. Thunderbird also supports PGP with the Enigmail extension, allowing you to digitally sign, and encrypt your email.


**Document Typesetting**
: LaTeX with Tectonic. Formal research papers are usually written with LaTeX, and most journals will only accept papers in this format. LaTeX (pronounced 'Lah-Tek') is a powerful typesetting tool where you write in a markup language and compile it to a nice document after. Besides producing professional looking documents, LaTeX also produce good looking mathematical equations, making it the choice for most STEM fields.

: Markdown. For simpler tasks and general writing, I uses Markdown which again as its name might suggests, is also a markup language. It is much more simpler to use than LaTeX, but still allow you to write arbitrary LaTeX codes in it. Writting in markup languages means that I can quickly edit and compile documents with very little hassle, as compared to waiting for MS Word to start. Recently, I am starting to use more of R Markdown instead of Markdown, due to its ability to run R and Python codes during compilation.

: Pandoc. The real star of the show here is Pandoc. Pandoc is a document converter, allowing you to convert between various file formats. Pandoc is also the program that allows the conversion of Markdown to .pdf with the help of LaTeX. You can write a document in MS Word, and convert to Markdown, or you can convert a Jupyter notebook to MS Powerpoint and more.

: Groff. Groff is unconventional, unless you have written a man page before. Groff is lightweight, fast, and pre-installed in most GNU/Linux systems. It's an extremely quick way for me to cook up a nice document without having to install huge programs like LaTeX and Pandoc.

: Here's a comparison: LaTeX, Markdown, Groff.
<br>
Markdown is certainly the simplest and produce nearly identical documents to LaTeX. Groff's syntax is also quite simple, but require some getting use to as they are not as intuitive.

: Even though, I no longer use MS Word, people send .docx files to me all the time. Abiword, being lightweight and fast is a one possible way to open .docx quickly. Although, most of the time I would simply convert the .docx to a .pdf using Pandoc.


**Presentation**
: LaTeX-beamer and Markdown with Pandoc. With the power of Pandoc, Markdown files can also be converted to LaTeX-beamer presentation slides, saving us the trouble of writing in LaTeX's long-winded syntax. In fact with Pandoc, you can also convert to HTML slides such as Slidy and reveal.js.

: Here's an example written in Markdown and converted to beamer using Pandoc: beamer.
<br>
Beamer looks ugly by default, but with its huge combination of themes and colour themes, something nice can come out of it.

: Another intriguing tool is suckless sent, which I use for informal presentation slides. sent lets you write your slides in plaintext and encourages the Takahashi method of presentation.
<br>
Here's an example: sent.


**Spreadsheets**
: Gnumeric (Ughh... no SSL for this site, what year is it?). In case you haven't noticed after reading all the way here, I have completely ditched Microsoft Office. There are simply better and more lightweight alternatives. For spreadsheets, Gnumeric is a fast alternative to MS Excel to open .xlsx files.

: pandas and R.
<br>
In research however, most people have grown out of .xlsx files, and instead handles more general data exchange formats, such as .csv. This is due partly to how large most datasets are, which MS Excel would take a long time to load, and partly due to how general formats, like .csv can be parsed with almost every tools. The pandas library for Python and the R programming language are good choices to deal with large datasets. They allow quick loading, analysis, manipulation, and plotting of data.


**Document Reader**
: Zathura on GNU/Linux and Sumatra PDF on Windows. I used to hate the .pdf format as Adobe Reader always take quite awhile to start up and the program feels bloated and slow. But now I know better and chose my own readers. Zathura and Sumatra PDF are lightweight and quick to open, as someone who is required to read a lot of .pdf files, this is essential. While Sumatra PDF can open other document formats by default, such as DjVu and ePub, Zathura is a modular program, allowing you to install additional plugins if you need to view additional file formats.


**Text Editor/Programming**
: neovim fulfils all of my text and programming tasks being quick to start up and highly configurable. neovim is based on Vim, which is lightweight, fast, powerful, customisable, and pre-installed on most Unix systems (GNU/Linux and MacOS). Vim is also the top 5 most popular editor in Stack Overflow's 2019 survey. Vim is extremely unique, and have a steep learning curve. It completely removes the need for you to use the mouse.

: It's key presses are unconventional and unlike standard word processing or editors programs. But once mastered, Vim's key bindings will be only way you will be comfortable with. In fact, many programs have add-ons or plugins that implement Vim's key bindings, and I have already completely lived by Vim's key bindings. Everything from scrolling through .pdf and images, navigating videos or my file manager, and browsing the web , I cannot live without Vim keys.

: VSCodium. If you are not ready for Vim yet, VSCodium is also a good editor (which also have add-ons for Vim keys by the way). In the survey linked above, you might have noticed that Visual Studio Code (VSCode) is ranked at the top, accounting for 50% of the 87317 survey respondents. Microsoft's VSCode has a non-free license, and contains Microsoft's customisations such as sending telemetry data to their servers. VSCodium on the other hand, is a freely-licensed version (MIT license) of VSCode, and is the recommended version if you care about free software.
